/**
 * Permission constants - Aligned with backend (/src/constants/permission.js)
 * These are used throughout the application for permission checks
 */
export const PERMISSIONS = {
  // Sales Operations
  CREATE_SALE: "CREATE_SALE",
  VOID_SALE: "VOID_SALE",
  VIEW_SALES: "VIEW_SALES",
  APPLY_DISCOUNT: "APPLY_DISCOUNT",

  // Returns
  CREATE_RETURN: "CREATE_RETURN",
  VIEW_RETURNS: "VIEW_RETURNS",

  // Reports
  VIEW_PROFIT_REPORT: "VIEW_PROFIT_REPORT",
  VIEW_SALES_REPORT: "VIEW_SALES_REPORT",
  EXPORT_REPORTS: "EXPORT_REPORTS",

  // User Management
  CREATE_USER: "CREATE_USER",
  VIEW_USERS: "VIEW_USERS",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_OWN_PROFILE: "UPDATE_OWN_PROFILE",

  // Role Management
  MANAGE_ROLES: "MANAGE_ROLES",
  ASSIGN_ROLES: "ASSIGN_ROLES",
  VIEW_ROLES: "VIEW_ROLES",

  // User Management
  CREATE_USER: "CREATE_USER",
  VIEW_USERS: "VIEW_USERS",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  USER_CREATE: "USER_CREATE",

  // Permission Management
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
  ASSIGN_PERMISSIONS: "ASSIGN_PERMISSIONS",

  // Category Management
  CREATE_CATEGORY: "CREATE_CATEGORY",
  VIEW_CATEGORIES: "VIEW_CATEGORIES",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",

  // Product Management
  CREATE_PRODUCT: "CREATE_PRODUCT",
  VIEW_PRODUCTS: "VIEW_PRODUCTS",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",

  // Inventory
  MANAGE_INVENTORY: "MANAGE_INVENTORY",
  VIEW_INVENTORY: "VIEW_INVENTORY",

  // Repair Management
  CREATE_REPAIR: "CREATE_REPAIR",
  VIEW_REPAIRS: "VIEW_REPAIRS",
  VIEW_OWN_REPAIRS: "VIEW_OWN_REPAIRS",
  ASSIGN_REPAIR: "ASSIGN_REPAIR",
  UPDATE_REPAIR: "UPDATE_REPAIR",
  COMPLETE_REPAIR: "COMPLETE_REPAIR",
  COLLECT_REPAIR_PAYMENT: "COLLECT_REPAIR_PAYMENT",
  CANCEL_REPAIR: "CANCEL_REPAIR",

  // Warranty Management
  CREATE_WARRANTY: "CREATE_WARRANTY",
  VIEW_WARRANTIES: "VIEW_WARRANTIES",
  UPDATE_WARRANTY: "UPDATE_WARRANTY",
  VOID_WARRANTY: "VOID_WARRANTY",
  CREATE_WARRANTY_CLAIM: "CREATE_WARRANTY_CLAIM",
  VIEW_WARRANTY_REPORTS: "VIEW_WARRANTY_REPORTS",

  // Settings
  MANAGE_SETTINGS: "MANAGE_SETTINGS",

  // Promotions
  MANAGE_PROMOTIONS: "MANAGE_PROMOTIONS",
  VIEW_PROMOTIONS: "VIEW_PROMOTIONS",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/**
 * Permission groups for easier management
 */
export const PERMISSION_GROUPS = {
  SALES: [
    PERMISSIONS.CREATE_SALE,
    PERMISSIONS.VOID_SALE,
    PERMISSIONS.VIEW_SALES,
    PERMISSIONS.APPLY_DISCOUNT,
  ],
  RETURNS: [
    PERMISSIONS.CREATE_RETURN,
    PERMISSIONS.VIEW_RETURNS,
  ],
  REPORTS: [
    PERMISSIONS.VIEW_PROFIT_REPORT,
    PERMISSIONS.VIEW_SALES_REPORT,
    PERMISSIONS.EXPORT_REPORTS,
  ],
  USER_MANAGEMENT: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,
  ],
  ROLE_MANAGEMENT: [
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.ASSIGN_ROLES,
    PERMISSIONS.MANAGE_PERMISSIONS,
    PERMISSIONS.ASSIGN_PERMISSIONS,
  ],
  PRODUCT_MANAGEMENT: [
    PERMISSIONS.CREATE_PRODUCT,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.UPDATE_PRODUCT,
    PERMISSIONS.DELETE_PRODUCT,
  ],
  CATEGORY_MANAGEMENT: [
    PERMISSIONS.CREATE_CATEGORY,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.UPDATE_CATEGORY,
    PERMISSIONS.DELETE_CATEGORY,
  ],
  INVENTORY: [
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY,
  ],
  REPAIR: [
    PERMISSIONS.CREATE_REPAIR,
    PERMISSIONS.VIEW_REPAIRS,
    PERMISSIONS.VIEW_OWN_REPAIRS,
    PERMISSIONS.ASSIGN_REPAIR,
    PERMISSIONS.UPDATE_REPAIR,
    PERMISSIONS.COMPLETE_REPAIR,
    PERMISSIONS.COLLECT_REPAIR_PAYMENT,
    PERMISSIONS.CANCEL_REPAIR,
  ],
  WARRANTY: [
    PERMISSIONS.CREATE_WARRANTY,
    PERMISSIONS.VIEW_WARRANTIES,
    PERMISSIONS.UPDATE_WARRANTY,
    PERMISSIONS.VOID_WARRANTY,
    PERMISSIONS.CREATE_WARRANTY_CLAIM,
    PERMISSIONS.VIEW_WARRANTY_REPORTS,
  ],
  SETTINGS: [
    PERMISSIONS.MANAGE_SETTINGS,
  ],
  PROMOTIONS: [
    PERMISSIONS.MANAGE_PROMOTIONS,
    PERMISSIONS.VIEW_PROMOTIONS,
  ],
} as const;

/**
 * Get all permissions as an array
 */
export function getAllPermissions(): Permission[] {
  return Object.values(PERMISSIONS);
}

/**
 * Get permissions for a group
 */
export function getPermissionsByGroup(group: keyof typeof PERMISSION_GROUPS): readonly Permission[] {
  return PERMISSION_GROUPS[group];
}
